app:
  name: ""
  domain: ""
  secretKey: ""

server:
  host: ""
  port: ""

db:
  name: ""
  user: ""
  pass: ""
  host: ""
  port: ""

auth:
  issuer: ""
  audience: ""
  accessExpiry:
  refreshExpiry:
