package realtime

import (
	"context"
	"encoding/json"
	"net/http/httptest"
	"strings"
	"testing"
	"time"

	"github.com/gorilla/websocket"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"drawo/config"
	"drawo/internal/core/domain"
	"drawo/internal/core/ports/repositories"
	"drawo/internal/core/ports/services"
	"drawo/internal/infrastructure/cache"
	"drawo/pkg/security"
)

func newWSServer(h *Handler) *httptest.Server {
	srv := httptest.NewServer(h)
	return srv
}

func newTestJWT(cfg config.Config) *security.JWTManager {
	return security.NewJWTManager(cfg.App.SecretKey, cfg.Auth.Issuer, cfg.Auth.AccessTokenExpiry, cfg.Auth.RefreshTokenExpiry)
}

func issueTestToken(t *testing.T, jwt *security.JWTManager, sessions repositories.SessionRepository, userID, sessID, tokID string) (string, string) {
	t.Helper()
	require.NoError(t, sessions.Set(context.Background(), &domain.Session{
		ID: sessID, UserID: userID, RefreshTokenID: tokID,
		ExpiresAt: time.Now().Add(time.Hour), CreatedAt: time.Now(),
	}))
	access, refresh, err := jwt.GenerateTokenPair(userID, sessID, tokID)
	require.NoError(t, err)
	return access, refresh
}

// fakeUserLookup satisfies realtime.UserLookup for WebSocket handler tests so
// player_joined/game_state carry usernames for registered users.
type fakeUserLookup struct {
	users map[string]*domain.User
}

func (f *fakeUserLookup) GetByID(_ context.Context, id string) (*domain.User, error) {
	if f.users == nil {
		return nil, nil
	}
	return f.users[id], nil
}

type guestWSTestEnv struct {
	*wsTestEnv
	roomSvc  services.RoomService
	users    *fakeUserLookup
	room     *domain.Room
	ownerID  string
	ownerAccess string
}

func newGuestWSTestEnv(t *testing.T) *guestWSTestEnv {
	t.Helper()
	cfg := config.Get()
	cfg.App.SecretKey = "ws-guest-secret"
	cfg.App.Domain = "http://example.com"
	cfg.Auth.Issuer = "drawo"
	cfg.Auth.AccessTokenExpiry = time.Hour
	cfg.Auth.RefreshTokenExpiry = 24 * time.Hour

	cacheClient, err := cache.NewClient(config.CacheConfig{Driver: "memory"})
	require.NoError(t, err)
	t.Cleanup(func() { _ = cacheClient.Close() })

	sessions := repositories.NewSessionRepo(cacheClient)
	roomRepo := repositories.NewRoomRepo(cacheClient)
	hub := NewHubWithDependencies(roomRepo, nil, nil)
	roomSvc := services.NewRoomService(roomRepo)
	users := &fakeUserLookup{users: map[string]*domain.User{
		"owner-1": {ID: "owner-1", Username: "TheOwner"},
		"user-2":  {ID: "user-2", Username: "Friend"},
	}}
	handler := NewHandler(cfg, hub, sessions, roomSvc, users)
	server := newWSServer(handler)
	t.Cleanup(server.Close)
	jwt := newTestJWT(cfg)

	ctx := context.Background()
	pw := "secret123"
	room, err := roomSvc.CreateRoom(ctx, "owner-1", domain.RoomTypePrivate, services.RoomSettings{
		Name: "Private", Password: &pw, Language: "en", MaxPlayers: 6, MaxRounds: 3,
		RoundTime: 40, WordSource: domain.WordSourceDefault,
	})
	require.NoError(t, err)
	// The invite code is generated by the service; store it for tests.
	require.NotEmpty(t, room.InviteCode)

	ownerAccess, _ := issueTestToken(t, jwt, sessions, "owner-1", "sess-owner", "tok-owner")

	return &guestWSTestEnv{
		wsTestEnv: &wsTestEnv{
			cfg:      cfg,
			sessions: sessions,
			roomRepo: roomRepo,
			hub:      hub,
			handler:  handler,
			server:   server,
			jwt:      jwt,
		},
		roomSvc:     roomSvc,
		users:       users,
		room:        room,
		ownerID:     "owner-1",
		ownerAccess: ownerAccess,
	}
}

func connectGuestWS(t *testing.T, e *guestWSTestEnv, guestToken string) *websocket.Conn {
	t.Helper()
	conn := e.dial(t)
	writeEnvelope(t, conn, EventAuth, AuthPayload{GuestToken: guestToken})
	writeEnvelope(t, conn, EventJoin, JoinPayload{Mode: "private", InviteCode: e.room.InviteCode})
	first := readEnvelopeWithDeadline(t, conn)
	assert.Equal(t, EventAuthOK, first.Type)
	joined := readUntilType(t, conn, EventJoined)
	var joinedPayload JoinedPayload
	require.NoError(t, json.Unmarshal(joined.Payload, &joinedPayload))
	assert.Equal(t, e.room.ID, joinedPayload.RoomID)
	return conn
}

func drainGameState(t *testing.T, conn *websocket.Conn) GameStatePayload {
	t.Helper()
	msg := readUntilType(t, conn, EventGameState)
	var gs GameStatePayload
	require.NoError(t, json.Unmarshal(msg.Payload, &gs))
	return gs
}

func TestWebSocketHandler_GuestJoinViaInviteAndPlayerList(t *testing.T) {
	env := newGuestWSTestEnv(t)
	ctx := context.Background()

	// Owner connects first.
	ownerConn := connectAuthenticated(t, env.wsTestEnv, env.ownerAccess, env.room.ID)
	gs := drainGameState(t, ownerConn)
	require.Len(t, gs.Players, 1)
	assert.Equal(t, "TheOwner", gs.Players[0].Username)
	assert.True(t, gs.Players[0].IsOwner)
	assert.False(t, gs.Players[0].IsGuest)

	// Guest joins via HTTP Join (password-checked), then opens WS with guest_token.
	joined, err := env.roomSvc.JoinRoom(ctx, env.room.InviteCode, "secret123")
	require.NoError(t, err)
	require.Equal(t, env.room.ID, joined.ID)
	guest, err := env.roomSvc.IssueGuestToken(ctx, env.room.ID, "   Alice   ")
	require.NoError(t, err)
	require.True(t, domain.IsGuestID(guest.GuestID))

	guestConn := connectGuestWS(t, env, guest.Token)
	guestGS := drainGameState(t, guestConn)
	require.Len(t, guestGS.Players, 2)
	var ownerP, guestP *PlayerState
	for i := range guestGS.Players {
		p := &guestGS.Players[i]
		if p.UserID == env.ownerID {
			ownerP = p
		}
		if p.UserID == guest.GuestID {
			guestP = p
		}
	}
	require.NotNil(t, ownerP)
	require.NotNil(t, guestP)
	assert.True(t, ownerP.IsOwner)
	assert.Equal(t, "TheOwner", ownerP.Username)
	assert.True(t, guestP.IsGuest)
	assert.False(t, guestP.IsOwner)
	assert.Equal(t, "Alice", guestP.Username)

	// Owner should have received player_joined broadcast for the guest.
	broadcast := readUntilType(t, ownerConn, EventPlayerJoined)
	var pb PlayerEventPayload
	require.NoError(t, json.Unmarshal(broadcast.Payload, &pb))
	assert.Equal(t, guest.GuestID, pb.UserID)
	assert.Equal(t, "Alice", pb.Username)

	// Clean closes.
	_ = ownerConn.Close()
	_ = guestConn.Close()
}

func TestWebSocketHandler_GuestRequiresBoundRoom(t *testing.T) {
	env := newGuestWSTestEnv(t)
	ctx := context.Background()

	// Mint a second room and a guest for it, then try to join env.room using that token.
	pw := "secret123"
	other, err := env.roomSvc.CreateRoom(ctx, "owner-1", domain.RoomTypePrivate, services.RoomSettings{
		Name: "Other", Password: &pw, Language: "en", MaxPlayers: 4, MaxRounds: 2,
		RoundTime: 30, WordSource: domain.WordSourceDefault,
	})
	require.NoError(t, err)
	_, err = env.roomSvc.JoinRoom(ctx, other.InviteCode, "secret123")
	require.NoError(t, err)
	g, err := env.roomSvc.IssueGuestToken(ctx, other.ID, "Wrong")
	require.NoError(t, err)

	conn := env.dial(t)
	writeEnvelope(t, conn, EventAuth, AuthPayload{GuestToken: g.Token})
	// Send a join that targets the OTHER room's id rather than the one bound to
	// the guest token — hub must reject.
	writeEnvelope(t, conn, EventJoin, JoinPayload{RoomID: other.ID, InviteCode: env.room.InviteCode})

	msg := readUntilType(t, conn, EventError)
	assert.Contains(t, string(msg.Payload), "guest token does not match")
	_ = conn.Close()
}

func TestWebSocketHandler_GuestAuthRejectedWhenNoRoomLookup(t *testing.T) {
	// Handlers built without a room lookup cannot authenticate guests.
	e := newWSTestEnv(t)
	e.createRoom(t, "room-x")
	conn := e.dial(t)
	writeEnvelope(t, conn, EventAuth, AuthPayload{GuestToken: "anything"})
	msg := readUntilType(t, conn, EventError)
	assert.Contains(t, string(msg.Payload), "guest auth not available")
	_ = conn.Close()
}

func TestWebSocketHandler_InvalidAuthRejected(t *testing.T) {
	e := newWSTestEnv(t)
	e.createRoom(t, "room-x")

	// Neither access nor guest token.
	conn := e.dial(t)
	writeEnvelope(t, conn, EventAuth, AuthPayload{})
	msg := readUntilType(t, conn, EventError)
	assert.Contains(t, string(msg.Payload), "access_token or guest_token is required")
	_ = conn.Close()

	// Non-JSON auth payload.
	conn2 := e.dial(t)
	require.NoError(t, conn2.WriteMessage(websocket.TextMessage, []byte(`{"type":"auth","payload":"bad"}`)))
	msg2 := readUntilType(t, conn2, EventError)
	assert.Contains(t, string(msg2.Payload), "invalid auth payload")
	_ = conn2.Close()
}

func TestWebSocketHandler_JoinValidation(t *testing.T) {
	e := newWSTestEnv(t)
	access, _ := e.createSession(t, "u1", "s1", "t1")
	conn := e.dial(t)
	writeEnvelope(t, conn, EventAuth, AuthPayload{AccessToken: access})
	// Empty/absent payload is fine — backend defaults to public matchmaking.
	writeEnvelope(t, conn, EventJoin, JoinPayload{})
	// But a mode that is not public/private/reconnect must fail.
	// Send it on a NEW connection because a bad join closes the socket.
	_ = conn.Close()

	conn2 := e.dial(t)
	writeEnvelope(t, conn2, EventAuth, AuthPayload{AccessToken: access})
	require.NoError(t, conn2.WriteJSON(MessageEnvelope{
		Type:    EventJoin,
		Payload: json.RawMessage(`{"mode":"bogus"}`),
	}))
	msg := readUntilType(t, conn2, EventError)
	assert.Contains(t, string(msg.Payload), "invalid join mode")
	_ = conn2.Close()

	// Missing invite_code for private mode.
	conn3 := e.dial(t)
	writeEnvelope(t, conn3, EventAuth, AuthPayload{AccessToken: access})
	writeEnvelope(t, conn3, EventJoin, JoinPayload{Mode: "private"})
	msg = readUntilType(t, conn3, EventError)
	assert.Contains(t, string(msg.Payload), "invite_code is required")
	_ = conn3.Close()
}

func TestWebSocketHandler_OwnerStartsGameOverWS(t *testing.T) {
	env := newGuestWSTestEnv(t)
	origCD := countdownDuration
	countdownDuration = 20 * time.Second
	t.Cleanup(func() { countdownDuration = origCD })

	access2, _ := env.createSession(t, "user-2", "sess-2", "tok-2")

	// Connect owner alone: no countdown (only one player).
	ownerConn := connectAuthenticated(t, env.wsTestEnv, env.ownerAccess, env.room.ID)
	_ = drainGameState(t, ownerConn)

	// Before friend joins, bump min-players so joining the second player does
	// NOT trigger the auto-countdown branch in handleJoin.
	r, err := env.hub.GetOrStartRoom(context.Background(), env.room.ID)
	require.NoError(t, err)
	r.state.MinPlayers = 99

	friendConn := connectAuthenticated(t, env.wsTestEnv, access2, env.room.ID)
	// Drain owner's player_joined broadcast and the post-join game_state on both
	// sockets before issuing any commands — otherwise those queued messages
	// surface in front of our start response.
	ownerJoined := readUntilType(t, ownerConn, EventPlayerJoined)
	var ownerPBP PlayerEventPayload
	require.NoError(t, json.Unmarshal(ownerJoined.Payload, &ownerPBP))
	assert.Equal(t, "user-2", ownerPBP.UserID)
	friendInit := drainGameState(t, friendConn)
	_ = drainGameState(t, ownerConn)
	require.Equal(t, GameStateWaitingForPlayers, friendInit.State, "auto-countdown must not fire during test")

	// Drop min back down so manual start succeeds (2 players present).
	r.state.MinPlayers = 2

	// Non-owner cannot start the game.
	writeEnvelope(t, friendConn, EventGame, GameEventPayload{Event: "start"})
	errMsg := readUntilType(t, friendConn, EventError)
	assert.Contains(t, string(errMsg.Payload), "only the room owner")

	// Owner starts the countdown over WS.
	writeEnvelope(t, ownerConn, EventGame, GameEventPayload{Event: "start"})

	gs := readUntilType(t, ownerConn, EventGameState)
	var ownerGS GameStatePayload
	require.NoError(t, json.Unmarshal(gs.Payload, &ownerGS))
	assert.Equal(t, GameStateCountdown, ownerGS.State)

	gs2 := readUntilType(t, friendConn, EventGameState)
	var friendGS GameStatePayload
	require.NoError(t, json.Unmarshal(gs2.Payload, &friendGS))
	assert.Equal(t, GameStateCountdown, friendGS.State)
	assert.Len(t, friendGS.Players, 2)

	// Starting again mid-countdown is rejected.
	writeEnvelope(t, ownerConn, EventGame, GameEventPayload{Event: "start"})
	errMsg = readUntilType(t, ownerConn, EventError)
	assert.Contains(t, string(errMsg.Payload), "already in progress")

	_ = ownerConn.Close()
	_ = friendConn.Close()
}

func TestWebSocketHandler_OwnerCannotStartAlone(t *testing.T) {
	env := newGuestWSTestEnv(t)
	ownerConn := connectAuthenticated(t, env.wsTestEnv, env.ownerAccess, env.room.ID)
	_ = drainGameState(t, ownerConn)

	writeEnvelope(t, ownerConn, EventGame, GameEventPayload{Event: "start"})
	msg := readUntilType(t, ownerConn, EventError)
	assert.Contains(t, string(msg.Payload), "at least 2 players")
	_ = ownerConn.Close()
}

func TestWebSocketHandler_InvalidGameEvents(t *testing.T) {
	env := newGuestWSTestEnv(t)
	access2, _ := env.createSession(t, "user-2", "sess-2", "tok-2")
	ownerConn := connectAuthenticated(t, env.wsTestEnv, env.ownerAccess, env.room.ID)
	_ = drainGameState(t, ownerConn)
	friendConn := connectAuthenticated(t, env.wsTestEnv, access2, env.room.ID)
	_ = drainGameState(t, friendConn)

	// Bad JSON payload.
	writeEnvelope(t, ownerConn, EventGame, "not-json")
	m := readUntilType(t, ownerConn, EventError)
	assert.Contains(t, string(m.Payload), "invalid game event")

	// Unknown event.
	writeEnvelope(t, ownerConn, EventGame, map[string]string{"event": "fly"})
	m = readUntilType(t, ownerConn, EventError)
	assert.Contains(t, string(m.Payload), "unsupported game event")

	_ = ownerConn.Close()
	_ = friendConn.Close()
}

func TestWebSocketHandler_ClearCanvasBroadcast(t *testing.T) {
	env := newGuestWSTestEnv(t)
	ownerConn := connectAuthenticated(t, env.wsTestEnv, env.ownerAccess, env.room.ID)
	_ = drainGameState(t, ownerConn)
	access2, _ := env.createSession(t, "user-2", "sess-2", "tok-2")
	friendConn := connectAuthenticated(t, env.wsTestEnv, access2, env.room.ID)
	_ = drainGameState(t, friendConn)

	// Force drawer state so draw ops/clear are allowed.
	room, err := env.hub.GetOrStartRoom(context.Background(), env.room.ID)
	require.NoError(t, err)
	room.gameState = GameStateDrawing
	room.state.CurrentDrawerID = env.ownerID
	room.roundEndsAt = time.Now().Add(time.Minute)

	writeEnvelope(t, ownerConn, EventClearCanvas, map[string]any{})
	msg := readUntilType(t, friendConn, EventClearCanvas)
	assert.Equal(t, EventClearCanvas, msg.Type)
	_ = ownerConn.Close()
	_ = friendConn.Close()
}

func TestWebSocketHandler_PrivateInviteCodeJoinForRegisteredUser(t *testing.T) {
	env := newGuestWSTestEnv(t)
	access2, _ := env.createSession(t, "user-2", "sess-2", "tok-2")
	conn := env.dial(t)
	writeEnvelope(t, conn, EventAuth, AuthPayload{AccessToken: access2})
	writeEnvelope(t, conn, EventJoin, JoinPayload{Mode: "private", InviteCode: env.room.InviteCode})
	first := readEnvelopeWithDeadline(t, conn)
	assert.Equal(t, EventAuthOK, first.Type)
	joined := readUntilType(t, conn, EventJoined)
	var jp JoinedPayload
	require.NoError(t, json.Unmarshal(joined.Payload, &jp))
	assert.Equal(t, env.room.ID, jp.RoomID)
	_ = conn.Close()
}

func TestWebSocketHandler_BadInviteRejected(t *testing.T) {
	env := newGuestWSTestEnv(t)
	access2, _ := env.createSession(t, "user-2", "sess-2", "tok-2")
	conn := env.dial(t)
	writeEnvelope(t, conn, EventAuth, AuthPayload{AccessToken: access2})
	writeEnvelope(t, conn, EventJoin, JoinPayload{Mode: "private", InviteCode: "ZZZZZZ"})
	msg := readUntilType(t, conn, EventError)
	assert.True(t, strings.Contains(string(msg.Payload), "private room not found") ||
		strings.Contains(string(msg.Payload), "room not found"))
	_ = conn.Close()
}
