ALTER TABLE player_statistics
    ADD COLUMN IF NOT EXISTS ranked_games BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS private_games BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS total_score BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS best_game_score BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS mvps BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS successful_drawings BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS games_abandoned BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS reports_received BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS reports_confirmed BIGINT NOT NULL DEFAULT 0;
